### ISSUE TITLE
Exception in GlobalLogger

### ISSUE THREAD

**Issue by yupinghuang** [ovro-lwa/lwa-issues#226]
calim08

```
Jan  5 21:27:35 lwacalim08 dr-vslow-15[60773]: Exception in thread GlobalLogger:
Jan  5 21:27:35 lwacalim08 dr-vslow-15[60773]: Traceback (most recent call last):
Jan  5 21:27:35 lwacalim08 dr-vslow-15[60773]:  File "/home/pipeline/.conda/envs/datarecorder/lib/python3.6/threading.py", line 916, in _bootstrap_inner
Jan  5 21:27:35 lwacalim08 dr-vslow-15[60773]:    self.run()
Jan  5 21:27:35 lwacalim08 dr-vslow-15[60773]:  File "/home/pipeline/.conda/envs/datarecorder/lib/python3.6/threading.py", line 864, in run
Jan  5 21:27:35 lwacalim08 dr-vslow-15[60773]:    self._target(*self._args, **self._kwargs)
Jan  5 21:27:35 lwacalim08 dr-vslow-15[60773]:  File "/home/pipeline/ovro_data_recorder/monitoring.py", line 564, in main
Jan  5 21:27:35 lwacalim08 dr-vslow-15[60773]:    self.storage.main(once=True)
Jan  5 21:27:35 lwacalim08 dr-vslow-15[60773]:  File "/home/pipeline/ovro_data_recorder/monitoring.py", line 266, in main
Jan  5 21:27:35 lwacalim08 dr-vslow-15[60773]:    self._manage_quota()
Jan  5 21:27:35 lwacalim08 dr-vslow-15[60773]:  File "/home/pipeline/ovro_data_recorder/monitoring.py", line 227, in _manage_quota
Jan  5 21:27:35 lwacalim08 dr-vslow-15[60773]:    while total_size > self.quota and len(files) > 1:
Jan  5 21:27:35 lwacalim08 dr-vslow-15[60773]: NameError: name 'files' is not defined
```

**Comment by jaycedowell** [comment]
Addressed with https://github.com/lwa-project/ovro_data_recorder/commit/ada446bf7b599c0c2b8d58d1b9fa66afa1a9ef90.
