### ISSUE TITLE
reset() of python ARX client v1.0.0 fails

### ISSUE THREAD

**Issue by rh-codebase** [ovro-lwa/lwa-issues#25]
stack trace returned:
`Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/lwautils/lwa_arx.py", line 287, in _check_rtn
    err = json.loads(err_msg_json)
  File "/home/ubuntu/anaconda3/lib/python3.7/json/__init__.py", line 348, in loads
    return _default_decoder.decode(s)
  File "/home/ubuntu/anaconda3/lib/python3.7/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/home/ubuntu/anaconda3/lib/python3.7/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 23 (char 22)
During handling of the above exception, another exception occurred:
:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/lwautils/lwa_arx.py", line 1746, in reset
    self._check_rtn(rtn, None)                                                                      
  File "/home/ubuntu/anaconda3/lib/python3.7/site-packages/lwautils/lwa_arx.py", line 289, in _check_rtn
    raise ARXE.ArxException("Unable to parse json error msg")                                           
lwautils.ArxException.ArxException: Unable to parse json error msg
`

**Comment by rh-codebase** [comment]
Fixed. verified it load memory contents 0 after a reset. Sched. for v1.0.1
