### ISSUE TITLE
lwa-feng-etcd@snap{i}.service starting up before etcd after system shutdown

### ISSUE THREAD

**Issue by yupinghuang** [ovro-lwa/lwa-issues#271]
Python logs an error but service did not transition to a stopped state (still shown to be "running").

``
Mar 01 22:42:43 lxdlwacr lwa_start_feng_etcd_service.py[24095]: 2023-03-01 22:42:43,222 - lwa_f.snap2_fengine:snap01 - INFO - Failed to poll stats from block powermon
Mar 01 22:42:54 lxdlwacr python[24095]: 2023-03-01 22:42:54,354 - /home/ubuntu/proj/lwa-shell/caltech-lwa/control_sw/scripts/lwa_start_feng_etcd_service.py:snap01 - ERROR - Error polling stats
                                        Traceback (most recent call last):
                                          File "/home/ubuntu/anaconda3/envs/casa/lib/python3.6/site-packages/etcd3/client.py", line 46, in handler
                                            return f(*args, **kwargs)
                                          File "/home/ubuntu/anaconda3/envs/casa/lib/python3.6/site-packages/etcd3/client.py", line 424, in put
                                            metadata=self.metadata
                                          File "/home/ubuntu/anaconda3/envs/casa/lib/python3.6/site-packages/grpc/_channel.py", line 946, in __call__
                                            return _end_unary_response_blocking(state, call, False, None)
                                          File "/home/ubuntu/anaconda3/envs/casa/lib/python3.6/site-packages/grpc/_channel.py", line 849, in _end_unary_response_blocking
                                            raise _InactiveRpcError(state)
                                        grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
                                                status = StatusCode.UNAVAILABLE
                                                details = "failed to connect to all addresses"
                                                debug_error_string = "{"created":"@1677710574.354339925","description":"Failed to pick subchannel","file":"src/core/ext/filters/client_channel/client_channel.cc","
                                        >
                                        
                                        During handling of the above exception, another exception occurred:
                                        
                                        Traceback (most recent call last):
                                          File "/home/ubuntu/anaconda3/envs/casa/lib/python3.6/site-packages/lwa_f/snap2_feng_etcd_client.py", line 635, in poll_stats
                                            self.set_top_status_good()
                                          File "/home/ubuntu/anaconda3/envs/casa/lib/python3.6/site-packages/lwa_f/snap2_feng_etcd_client.py", line 604, in set_top_status_good
                                            self.ec.put(self.top_status_key, json.dumps({"ok": True, "timestamp": t}))
                                          File "/home/ubuntu/anaconda3/envs/casa/lib/python3.6/site-packages/etcd3/client.py", line 48, in handler
                                            _translate_exception(exc)
                                          File "/home/ubuntu/anaconda3/envs/casa/lib/python3.6/site-packages/etcd3/client.py", line 32, in _translate_exception
                                            raise exception
                                        etcd3.exceptions.ConnectionFailedError: etcd connection failed
```

**Comment by jack-h** [comment]
Thanks for the report.
Reckless catch-all exception in the F-engine poll loop. Etcd errors will now cause the script to die and be restarted by systemd, so this should heal itself in the event the etcd server restarts
