### ISSUE TITLE
OWTE causes delayed returns

### ISSUE THREAD

**Issue by rh-codebase** [ovro-lwa/lwa-issues#29]
Running OWTE via the python ARX client raw command causes the following behavior. First a couple of commands which return expected results. Then the OWTE command with a 2.0 second user timeout. The exception raised indicates the ARX command timed out(set to 900ms). The command is repeated and succeeds. This is followed by a GETC2 which appears to return the same info as the previous command but the output is slightly different. Then repeated which is successful but the next ECHO commands returns the previous results and another ECHO appears to work, but it's the previous output. The next commands show this behavior using different ECHO strings. After ECHO12ab4, RSET is issued which returns the output of the previous ECHO12ab4. Another RSET times out and then an ECHO12ab5 return correctly. Finally another RSET times out.

`>>> ma.raw(2, 'ECHO12ab')
'ECHO12ab'
>>> ma.raw(2, 'GETC2')
'0001'
>>> ma.raw(2, 'OWTE', 2.0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/proj/lwa/lwa-pyutils/lwautils/lwa_arx.py", line 1221, in raw
    self._check_rtn(rtn)
  File "/home/ubuntu/proj/lwa/lwa-pyutils/lwautils/lwa_arx.py", line 289, in _check_rtn
    raise ARXE.ArxException(err_msg)
lwautils.ArxException.ArxException: CTO ARX command timeout exceeded.
>>> ma.raw(2, 'OWTE', 2.0)
'01A601A801AC01B001A701A701A101B701B2019A01AB0181019F01B201A801B3'
>>> ma.raw(2, 'GETC2')
'01A601A801AB01AF01A501A601A101B701B2019A01AB0181019F01B101A701B3'
>>> ma.raw(2, 'GETC2')
'0001'
>>> ma.raw(2, 'ECHO12ab')
'0001'
>>> ma.raw(2, 'ECHO12ab')
'ECHO12ab'
>>> ma.raw(2, 'ECHO12ab1')
'ECHO12ab'
>>> ma.raw(2, 'ECHO12ab2')
'ECHO12ab1'
>>> ma.raw(2, 'ECHO12ab3')
'ECHO12ab2'
>>> ma.raw(2, 'ECHO12ab4')
'ECHO12ab3'
>>> ma.raw(2, 'RSET')
'ECHO12ab4'
>>> ma.raw(2, 'RSET')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/proj/lwa/lwa-pyutils/lwautils/lwa_arx.py", line 1220, in raw
    rtn = self._send(arx_addr, 'raw', cmd, user_timeout)
  File "/home/ubuntu/proj/lwa/lwa-pyutils/lwautils/lwa_arx.py", line 362, in _send
    rtn = self.my_cr.send(cmd_key, cmd, val, user_timeout)
  File "/home/ubuntu/proj/lwa/lwa-pyutils/lwautils/cmd_rsp.py", line 166, in send
    raise toe.TimeoutException("User timeout reached")
lwautils.TimeoutException.TimeoutException: User timeout reached
>>> ma.raw(2, 'ECHOab5')
'ECHOab5'
>>> ma.raw(2, 'RSET')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/proj/lwa/lwa-pyutils/lwautils/lwa_arx.py", line 1220, in raw
    rtn = self._send(arx_addr, 'raw', cmd, user_timeout)
  File "/home/ubuntu/proj/lwa/lwa-pyutils/lwautils/lwa_arx.py", line 362, in _send
    rtn = self.my_cr.send(cmd_key, cmd, val, user_timeout)
  File "/home/ubuntu/proj/lwa/lwa-pyutils/lwautils/cmd_rsp.py", line 166, in send
    raise toe.TimeoutException("User timeout reached")
lwautils.TimeoutException.TimeoutException: User timeout reached
`

**Comment by rh-codebase** [comment]
Using another 485-USB device hooked up to another computer, it was determined that the ARX board was not locking up. Setting the serial read timeout for the OWTE command to 1.2 seconds has thus solved the problem. I'm fairly certain what is going on is the serial read is timing out but the ARX doesn't know this and eventually sends its data to the serial device. On the next command invocation, part of that data are then read. It may or may not start with an <ACK> depending on when the command timed out in relation to the ARX sending data. The service needs to flush the serial port buffer after a time out occurs but this is still fragile as there is no way to know when the ARX will send the data. It would be more robust if a fixed time is set in the ARX API and if collecting the temperatures can't be met by that time, then a <NAK> is returned. The service can then know when to flush the buffer and know that extra data won't be placed in it.
