### ISSUE TITLE
lwa_start_feng_etcd_service.py: there's None somewhere

### ISSUE THREAD

**Issue by yupinghuang** [ovro-lwa/lwa-issues#490]
```
Oct 31 23:48:09 lwacalim10 lwa_start_feng_[2059798]: 2023-10-31 23:48:09,667 - /opt/devel/pipeline/envs/deployment/bin/lwa_start_feng_etcd_service.py:snap02 - ERROR - Command failed
                                                     Traceback (most recent call last):
                                                       File "/opt/devel/pipeline/envs/deployment/lib/python3.6/site-packages/lwa_f/snap2_fengine.py", line 433, in program
                                                         self._cfpga.transport.upload_to_ram_and_program(fpgfile, force=force)
                                                       File "/opt/devel/pipeline/envs/deployment/lib/python3.6/site-packages/casperfpga/transport_tapcp.py", line 384, in upload_to_ram_and_program
                                                         meta_inflash = self.get_metadata()
                                                       File "/opt/devel/pipeline/envs/deployment/lib/python3.6/site-packages/casperfpga/transport_tapcp.py", line 259, in get_metadata
                                                         meta_page = self.read('/flash', READ_CHUNK_SIZE, offset=user_flash_loc + page_offset)
                                                     TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'
                                                     
                                                     During handling of the above exception, another exception occurred:
                                                     
                                                     Traceback (most recent call last):
                                                       File "/opt/devel/pipeline/envs/deployment/lib/python3.6/site-packages/lwa_f/snap2_feng_etcd_client.py", line 564, in _etcd_callback
                                                         resp = cmd_method(**cmd_kwargs)
                                                       File "/opt/devel/pipeline/envs/deployment/lib/python3.6/site-packages/lwa_f/snap2_fengine.py", line 436, in program
                                                         raise RuntimeError("Error during load")
                                                     RuntimeError: Error during load
Oct 31 23:48:09 lwacalim10 lwa_start_feng_[2059798]: 2023-10-31 23:48:09,672 - /opt/devel/pipeline/envs/deployment/bin/lwa_start_feng_etcd_service.py:snap02 - ERROR - Responded to command 'program' (ID 16987960>
```

looks like `user_flash_loc` might have been `None` and subsequent `program` commands will not run. Restarting the services seems to fix it.

**Comment by caseyjlaw** [comment]
See #491
