### ISSUE TITLE
ARX client does not timeout when etcd host machine disk's are full

### ISSUE THREAD

**Issue by rh-codebase** [ovro-lwa/lwa-issues#56]
The host disks running the MCS containers became full. This may be causing the ARX client to not timeout since the timeout is handled via a context in etcd. Also not present on the host is the ttyUSB0 device. The ARX service is still up however. 

After waiting some 2minutes for the arx client to timout, a Ctrl-C produced:
`>>> ma.get_board_info(35)
^CTraceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ubuntu/anaconda3/envs/casa/lib/python3.6/site-packages/lwautils/lwa_arx.py", line 1266, in get_board_info
    rtn = self._send(arx_addr, 'arxn', '',user_timeout)
  File "/home/ubuntu/anaconda3/envs/casa/lib/python3.6/site-packages/lwautils/lwa_arx.py", line 387, in _send
    rtn = self.my_cr.send(cmd_key, cmd, val, user_timeout)
  File "/home/ubuntu/anaconda3/envs/casa/lib/python3.6/site-packages/lwautils/cmd_rsp.py", line 152, in send
    self._mon_prefix_callback)
  File "/home/ubuntu/anaconda3/envs/casa/lib/python3.6/site-packages/dsautils/dsa_store.py", line 163, in add_watch_prefix
    watch_id = self.etcd.add_watch_prefix_callback(key, self._process_cb_prefix(cb_func))
  File "/home/ubuntu/anaconda3/envs/casa/lib/python3.6/site-packages/etcd3/client.py", line 46, in handler
    return f(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/casa/lib/python3.6/site-packages/etcd3/client.py", line 591, in add_watch_prefix_callback
    return self.add_watch_callback(key_prefix, callback, **kwargs)
  File "/home/ubuntu/anaconda3/envs/casa/lib/python3.6/site-packages/etcd3/client.py", line 46, in handler
    return f(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/casa/lib/python3.6/site-packages/etcd3/client.py", line 570, in add_watch_callback
    return self.watcher.add_callback(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/casa/lib/python3.6/site-packages/etcd3/watch.py", line 96, in add_callback
    self._new_watch_cond.wait(timeout=self.timeout)
  File "/home/ubuntu/anaconda3/envs/casa/lib/python3.6/threading.py", line 295, in wait
    waiter.acquire()
KeyboardInterrupt
`

**Comment by rh-codebase** [comment]
v1.4.0 of lwa-pyutils should fix this.
